[package]
name = "raindropdick"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["widgets","spider"]
[dependencies]
cursive = { git = "https://github.com/gyscos/cursive" }
#cursive = "0.15"
futures = "0.3"
base64 = "0.13.0"
surf = "2.1.0"
serde_json = "1.0"
[dependencies.async-std]
version = "1.7.0"
features = ["attributes"]
