[package]
name = "raindropdick"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["widgets","spider"]
[dependencies]
cursive = { git = "https://github.com/gyscos/cursive" }
#cursive = "0.15"
widgets = {path = "./widgets"}
spider = {path = "./spider"}
futures = "0.3"
[dependencies.async-std]
version = "1.7.0"
features = ["attributes"]
