[package]
name = "spider"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
surf = "2.1.0"
base64 = "0.13.0"

[dependencies.async-std]
version = "1.7.0"
features = ["attributes"]

